# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [235]:
import numpy as np

2. Create a null vector of size 10 

In [238]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

3. Create a vector with values ranging from 10 to 49

In [239]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3


In [240]:
a.shape

(40,)

5. Print the type of the previous array in question 3

In [241]:
# type shows data type in python,dtype will show type in NumPy.
print(type(a)) 
print(a.dtype)

<class 'numpy.ndarray'>
int32


6. Print the numpy version and the configuration


In [242]:
print(np.version.version)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SyedA/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SyedA/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SyedA/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SyedA/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SyedA/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SyedA/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SyedA/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SyedA/anaconda3\\Library\\include']
None



7. Print the dimension of the array in question 3


In [243]:
print(a)
a.ndim

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


1

8. Create a boolean array with all the True values

In [245]:
A = np.array([4, 4, 4, 4, 4, 4])
print(A == 4)

[ True  True  True  True  True  True]


9. Create a two dimensional array




In [246]:
a=np.array([[1,2,3,5],[1,2,3,4]])
a

array([[1, 2, 3, 5],
       [1, 2, 3, 4]])

10. Create a three dimensional array



In [247]:
a=np.array([[[1,2,3],[3,4,5],[6,7,8]]])
a

array([[[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [248]:
a=np.array([1,2,3,4,5])
print(a)
print(a[-1::-1])

[1 2 3 4 5]
[5 4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [249]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [250]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [251]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = np.array([1, 2, 3, 4, 5])*1.0
print(arr.dtype)

int32
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [252]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [253]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr=arr1==arr2
arr

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [254]:
arr=np.arange(0,10,3)
arr

array([0, 3, 6, 9])

18. Replace all odd numbers to -1 from previous array

In [255]:
arr=np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [256]:
na=np.arange(0,15)
na[5]=12
na[6]=12
na[7]=12
na[8]=12
na

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9, 10, 11, 12, 13, 14])


20. Create a 2d array with 1 on the border and 0 inside

In [257]:
ar_2d=np.eye(4,4)
ar_2d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [258]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [262]:
arr3d = np.array([[[1, 2, 3*64.0], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64., 64., 64.],
        [64., 64., 64.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [263]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[0][0:5]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [264]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[1][1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [304]:
t_d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(t_d)
print('\n',t_d[:2:,3])

[[0 1 2 3 4]
 [5 6 7 8 9]]

 [3 8]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [2]:
r_a=np.random.randint((10,10))
a=[10,8,9]
b=[5,4,3]
print('random numbers are ',r_a)
print(np.maximum(a,b))
print(r_a.max())
print(r_a.min())

random numbers are  [4 6]
[10  8  9]
6
4


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [132]:
a= np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.unique((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [307]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b,a,b)

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [311]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data)
print(np.where(names!='Will',names,'Will')

SyntaxError: unexpected EOF while parsing (<ipython-input-311-dc69219dccc0>, line 4)

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [134]:
t_d=np.array([[1,2,3,4,5],[1,2,3,5,6,7,8]])
t_d

<ipython-input-134-ceb7796e3336>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  t_d=np.array([[1,2,3,4,5],[1,2,3,5,6,7,8]])


array([list([1, 2, 3, 4, 5]), list([1, 2, 3, 5, 6, 7, 8])], dtype=object)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [138]:
b=np.array([[[1,2,3,4],[5,6,7,8]]])
b
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

33. Swap axes of the array you created in Question 32

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [99]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


NameError: name 'numpy' is not defined

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [234]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [7]:
r=np.random.randn(20)
print(r)
print('\n',r.cumsum())

[-0.64254145 -0.80994995 -1.04802491  0.86289713  1.29944725 -0.03757954
  1.71772903  0.07524206 -1.81245532  0.97065264  0.2161198  -0.29357977
  1.74880281 -1.31967396 -0.28512178  0.10820444 -1.10236382  0.39343429
  0.08622032  0.36247246]

 [-0.64254145 -1.45249139 -2.50051631 -1.63761918 -0.33817193 -0.37575148
  1.34197755  1.41721962 -0.3952357   0.57541694  0.79153674  0.49795697
  2.24675978  0.92708582  0.64196404  0.75016848 -0.35219534  0.04123895
  0.12745927  0.48993173]
